### ISSUE TITLE
error trying to bring up ums container

### ISSUE THREAD

**Issue by hgeorges** [mbentley/docker-ums#1]
Hello;
I am making the first steps with Docker, and I am interested in running /testing your ums docker image. I've pulled it onto my unraid server (which is running a slim version of slackware), and I tried to run the command you've suggested in your readme.
This is how it looks:
# docker run -d --net="host" --restart=always -v /mnt/user/Docker/appdata/ums:/opt/ums/UMS.conf -v /mnt/user/Docker/appdata/ums:/opt/ums/database -v /mnt/user/Film:/Media --name ums mbentley/ums

9c6ad7ee4aac6fbf9c808f3a4bb34ec596249368fb296929142aca0dbff33df9
FATA[0000] Error response from daemon: Cannot start container 9c6ad7ee4aac6fbf9c808f3a4bb34ec596249368fb296929142aca0dbff33df9: [8] System error: not a directory 
The directory /mnt/user/Docker/... is there created. I'm not sure what's wrong. Any chance you can  advise what is perhaps going on?
Thank you
hg

**Comment by mbentley** [comment]
Sorry for taking a while to reply.  Does the container run if you do not provide volumes?  I imagine it will:
`docker run -d --net="host" --restart=always --name ums mbentley/ums`

I am seeing issues in your volumes options.  If you want to mount just specific files into the container, you have to specify them in your `-v` options.  You're telling Docker to bind mount `/mnt/user/Docker/appdata/ums` to `UMS.conf` and the `database` directory and that is why it is failing.  Try this command:

```
docker run -d --net="host" --restart=always \
  -v /mnt/user/Docker/appdata/ums/UMS.conf:/opt/ums/UMS.conf \
  -v /mnt/user/Docker/appdata/ums/database:/opt/ums/database \
  -v /mnt/user/Film:/Media \
  --name ums \
  mbentley/ums
```

**Comment by hgeorges** [comment]
Thank you, Matt. That advice did the job. I'm not sure how to connect to the server now ... is there an management web interface to connect to for additional settings? Tried to find some references on-line and couldn't find anything too clear. 

Edit: found the web interface on port 9001, but there is really nothing in terms of media server management there. I'll continue to research how I can set it up further, and use it.

I have also another question relative to plugin setup - can you tell me where /how do I add those into your  container ?
Thank you,
horia

**Comment by mbentley** [comment]
There isn't a web user interface to configure UMS, at least not one that isn't a third party utility to the best of my knowledge.  You can, however, run UMS and bind mount in the X11 socket.  You can actually use these instructions and just modify the run command:
https://github.com/mbentley/docker-fsv/blob/master/README.md

So if you are running this on a Linux host where you have a X11 installed, you should be able to do this:

```
docker run -d --net="host" --restart=always \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e DISPLAY=unix$DISPLAY
  -v /mnt/user/Docker/appdata/ums/UMS.conf:/opt/ums/UMS.conf \
  -v /mnt/user/Docker/appdata/ums/database:/opt/ums/database \
  -v /mnt/user/Film:/Media \
  --name ums \
  mbentley/ums
```

There are also instructions for getting it to work on OS X if you're running this in a VM.

**Comment by hgeorges** [comment]
Thank you. I'll try that. But I'm afraid that I might have to install x11 as well in that container?
Barebones unraid server (http://lime-technology.com) has only a web interface.
Meanwhile I just deleted my docker file and I'm starting again. I'm not to sure if the container management on unraid cleans-up everything when deleting images & containers - so instead of relying on that, just deleted everything.
I'll load again ums. 
Do you mind updating your docker file to UMS 5.1.4 version?
As for plugins i assume I just declare one additional directory  (-v ...)?
Thank you

**Comment by mbentley** [comment]
It doesn't require X11 in the container but on the host you're running it
on so it probably won't work with that setup unfortunately.

I'll update the version this evening or tomorrow.

On Saturday, July 4, 2015, hgeorges notifications@github.com wrote:

> Thank you. I'll try that. But I'm afraid that I might have to install x11
> as well in that container?
> Barebones unraid server (http://lime-technology.com) has only a web
> interface.
> Meanwhile I just deleted my docker file and I'm starting again. I'm not to
> sure if the container management on unraid cleans-up everything when
> deleting images & containers - so instead of relying on that, just deleted
> everything.
> I'll load again ums.
> Do you mind updating your docker file to UMS 5.1.4 version?
> As for plugins i assume I just declare one additional directory (-v ...)?
> Thank you
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mbentley/docker-ums/issues/1#issuecomment-118556493.

## 

Matt Bentley
317.966.8225
