### ISSUE TITLE
Unhandled exception during library scan

### ISSUE THREAD

**Issue by vrtlspd** [mbentley/docker-ums#13]
It seems that UMS is unable to scan the library as it stops right at the first media file and doesn't progress through.

`ERROR 16:22:56.276 [Library Scanner] Unhandled exception during library scan: Malformed input or input contains unmappable characters: /media/[REC]�� (2009)`

I found some other docker container / fork of yours, [docker-ums](https://github.com/jk7gr/docker-ums) that claims to have UTF-8 support, but it's a very old version (UMS5)
Can you somehow fix this?

**Comment by mbentley** [comment]
Which image tag are you using?  Wasn't sure if there might be an issue with either the alpine, debian, or both.  Wouldn't surprise me if it is a relatively simple encoding issue but I'll just have to figure out what needs to be set. Could you provide an example file name that you can copy in as well so I can test?

**Comment by vrtlspd** [comment]
Sorry, forget to mention that. I'm using "10-debian-amd64" as "11-debian-amd64" refuses to run with another error: 
```
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

The mkv file is actually inside a directory with the name of the movie. The directory name is:
[REC]² (2009)

**Comment by mbentley** [comment]
Good deal.  Looks like I will be able to fix this fairly easily.  Thanks for the note about the 11 image as well.  I can use the newer `JAVA_OPTS="-XX:+UseContainerSupport"` option since `UseCGroupMemoryLimitForHeap` has been removed.

**Comment by mbentley** [comment]
Building some new images that should have a fix for `10-debian-amd64` and `11-debian-amd64`.  Should be done in a few minutes.

**Comment by mbentley** [comment]
OK, images should be up and available.  Seems to be working here with a directory named `[REC]² (2009)` now.  Adding the `locales` package and enabling `en_US.UTF-8`, then running `locale-gen` does the trick which was added [here](https://github.com/mbentley/docker-ums/blob/5d80ddcb9cb5cd18c3a41c572ab23173756c1c22/Dockerfile.10-debian#L10-L13).

**Comment by vrtlspd** [comment]
thank you. I'll test and let you know

**Comment by vrtlspd** [comment]
Yes, it's fixed. thank you

**Comment by mbentley** [comment]
Awesome, thanks for verifying!
